### PR TITLE
Auto change lead status.

### PR DESCRIPTION
**Pull request by thenav56**
Addresses
- #966
- #968

## Changes

- Add receiver to change lead status to IN_PROGRESS
- Move mutation test to separate file for lead.
- Change Lead Status Enum values.

Mention related users here if any.
@AdityaKhatri Lead Status Enum is changed.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

### CODE REVIEW

**Review by k9845 — DISMISSED** [review]
Shouldn't we change the older lead statuses and map them with the new statuses?

**Comment by thenav56** [comment]
> Shouldn't we change the older lead statuses and map them with the new statuses?

We are still not sure if this is the final status. For now, just changing the enum labels which should be enough for now. There is also a TODO.

**Comment by k9845** [comment]
> We are still not sure if this is the final status. For now, just changing the enum labels which should be enough for now. There is also a TODO.

Sounds cool.

**Review by bimal125 — DISMISSED** [review]
looks good for me

**Review by k9845 — APPROVED** [review]

**Pull request merged**
